# -*- coding: utf-8 -*-
"""PalmerPenguinsM2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_NH0ySPH5aXY2q-bz_SV5u51w_rLY0e
"""

# PalmerPenguinsM2.py
# KeylanFralick
# 9/12/26
# Caculates and displays Plamer Penguin statistics

# constants representing the species and count
import math
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

TOTAL_SPECIES = 3

NUM_Chinstrap = 68
NUM_Gentoo = 123
NUM_Adelie = 151

total_penguins = NUM_Chinstrap + NUM_Gentoo + NUM_Adelie
average_penguins = total_penguins / TOTAL_SPECIES

chinstrap_percent = NUM_Chinstrap / TOTAL_SPECIES * 100
gento_percent = NUM_Gentoo / TOTAL_SPECIES * 100
adelie_percent = NUM_Adelie / TOTAL_SPECIES * 100

average_penguins_rounded_up = math.ceil(average_penguins)

# output the species names with introductory text
print("Introducing the Palmer Penguins:")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")

print("There are a total of " +
      str(TOTAL_SPECIES) +
      " penguin species in this dataset.")
print("There are a total of " +
    str(total_penguins) +
    " penguins in the dataset.")
# To display a species count and percentage:
print("The average number of penguins per species is", average_penguins)
print("The average number rounded up is", average_penguins_rounded_up)

print() # This adds a blank space

print(SP_CHINSTRAP + ": " +
    str(NUM_Chinstrap) + " (" +
    str(chinstrap_percent) + "%)")
print(SP_CHINSTRAP + ": " +
    str(NUM_Gentoo) + " (" +
    str(gento_percent) + "%)")
print(SP_GENTOO + ": " +
    str(NUM_Adelie) + " (" +
    str(adelie_percent) + "%)")